### ISSUE TITLE
Current selected line syntax highlighting

### ISSUE THREAD

**Issue by danobi** [cdmedia/itg_flat_vim#6]
Not sure if intended but there is no syntax highlighting on the current line the cursor is on. This makes it hard to spot typos immediately.

**Comment by chrisdiana** [comment]
I agree highlighting should work on the current line (thought I already fixed that but I could be wrong). You're welcome to send a pull request if you have a fix. Thanks for the suggestion!

**Comment by danobi** [comment]
Ah, it looks like I forgot to update my repo. The issue was fixed.
